apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sabnzbd.serviceAccountName" . }}-trigger-sa
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded