apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sabnzbd.fullname" . }}-trigger-rb
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    #"helm.sh/hook-delete-policy": hook-succeeded
subjects:
- kind: ServiceAccount
  name: {{ include "sabnzbd.fullname" . }}-trigger-sa
roleRef:
  kind: Role
  name: {{ include "sabnzbd.fullname" . }}-trigger-role
  apiGroup: rbac.authorization.k8s.io