apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sabnzbd.fullname" . }}-trigger-role
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    #"helm.sh/hook-delete-policy": hook-succeeded
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ['{{ include "sabnzbd.fullname" . }}']
  verbs: ["get", "patch"]