apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: mqtt
    {{- if .Values.prometheus_export.enabled }}
    - port: {{ .Values.prometheus_export.port }}
      targetPort: {{ .Values.prometheus_export.port }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
