name: Helm chart release

on:
  repository_dispatch:
    types: [run-chart-release]

  workflow_dispatch:  # optioneel handmatig triggerbaar
    inputs:
      component:
        description: "Component to release"
        required: false
      version:
        description: "Version to release"
        required: false

jobs:
  release_chart:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: master
          fetch-depth: 0

      - uses: azure/setup-helm@v4.3.1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Log trigger info
        run: |
          echo "Triggered by dispatch event:"
          echo "Component: ${{ github.event.client_payload.component }}"
          echo "Version: ${{ github.event.client_payload.version }}"

          {
            echo "### Workflow variables"
            echo "| Variable   | Value       |"
            echo "| ---------- | ----------- |"
            echo "| COMPONENT | ${{ steps.get_tag_parts.outputs.COMPONENT }} |"
            echo "| VERSION   | ${{ steps.get_tag_parts.outputs.VERSION }} |"
          } >> $GITHUB_STEP_SUMMARY

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.HELM_RELEASE_TOKEN }}
